version: '3.4'

services:
  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
  customerapi:
    build:
      context: .
      dockerfile: CustomersApi/Dockerfile
    ports:
      - 8000:80
    depends_on:
      - rabbitmq
  orderapi:
    build:
      context: .
      dockerfile: OrderApi/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - rabbitmq
  productapi:
    build:
      context: .
      dockerfile: ProductApi/Dockerfile
    ports:
      - 8002:80
    depends_on:
      - rabbitmq
  prometheus:
    build:
      context: .
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15673:15672"